### ISSUE TITLE
Syntax Error with `.WithTableName` When Used with `GetItemAsync<TEntity>`

### ISSUE THREAD

**Issue by devtekve** [AllocZero/EfficientDynamoDb#235] opened 2024-05-08 16:49 UTC
### Description:

I am encountering a type mismatch error when attempting to set the table name dynamically using the `WithTableName` extension method, specifically after calling `GetItemAsync<TEntity>`. 

### Steps to Reproduce:

1. Execute `GetItemAsync<TEntity>` with necessary parameters to retrieve an item.
2. Chain the `WithTableName` method directly to the `GetItemAsync` call.
3. Note the syntax error produced.

### Expected Behavior:

The `WithTableName` method should change the target table, allowing for dynamic table name adjustments without resulting in type mismatch errors.

### Actual Behavior:

A type mismatch error is reported, indicating:
```
The type 'System.Threading.Tasks.Task<TEntity>' must be convertible to 'EfficientDynamoDb.Operations.Shared.ITableBuilder<System.Threading.Tasks.Task<TEntity>>' in order to use it as parameter 'TBuilder' in the generic method 'TBuilder EfficientDynamoDb.Extensions.TableNameExtensions.WithTableName<TBuilder>(this TBuilder, string)'
``` 
### Code Example:
```csharp
await context.GetItemAsync<TEntity>(key, sort).WithTableName("");
```

<img width="1172" alt="image" src="https://github.com/AllocZero/EfficientDynamoDb/assets/7696966/84c40aa5-b203-4d49-86f9-11ee9df232d6">

### Environment:

- EfficientDynamoDb version: `0.9.15`
- .NET version: `.net 8.0`
- Operating System: `macOS Sonoma 14.3.1`

**Comment by firenero** [comment] 2024-05-10 22:32
Hey @devtekve. To be able to chain `WithTableName` method you have to use the `context.GetItem()` method that returns a builder instead of executing the operation immediately. It must be the same for all other operations like `Query`, `Scan` and so on but let me know if that's not the case for you. 

The correct call based on your example can look like this:
```csharp
var entity = await context.GetItem<TEntity>().WithPrimaryKey(id, version)
    .WithTableName("")
    .ToItemAsync();
```

Let me know if that helps.

**Comment by devtekve** [comment] 2024-05-11 02:40
That's an excellent workaround! I was afraid of giving up the `async` but that's  a viable way!. 

However, the main issue is that I should not be able to see `.WithTableName()` option on intellisense if it can't be applied. I think the signature needs to be revisited. It gives the wrong idea that there's a mistake from the user, and that somehow you can make the extension work on `GetItemsAsync()` which I understand is never going to be the case, no matter what the user does.

**Comment by firenero** [comment] 2024-05-11 12:36
I don't know why it happens for you, but `.WithTableName()` shouldn't appear as an autocomplete option. It doesn't appear for me:
![image](https://github.com/AllocZero/EfficientDynamoDb/assets/9461703/c64e84a5-1a54-4398-8792-463bf220f655)

[WithTableName<TBuilder>()](https://github.com/AllocZero/EfficientDynamoDb/blob/58a416d63204864660a327005f4c66a67959570a/src/EfficientDynamoDb/Extensions/HighLevelExtensions.cs#L15) extension method has a generic constraint that only allows it to be applied for types that implement `ITableBuilder<TBuilder>` interface. `GetItemAsync()` returns Task<T> so it's not a valid target for this extension method.

**Comment by devtekve** [comment] 2024-05-11 14:24
Makes sense... I tested it and I am realizing it happens when the TestObj is generic. Here's how you can make it show up on your end: 

```csharp
public Task<T> DemoQuery<T>()
{
    return context.GetItemAsync<T>().WithTableName("");
}
```

<img width="824" alt="image" src="https://github.com/AllocZero/EfficientDynamoDb/assets/7696966/a23497f4-c4d6-4e8c-843f-cda365404360">

**Comment by firenero** [comment] 2024-05-11 14:57
I can reproduce it on my side but it looks like a bug in IDE because clearly, you can't use this extension method because the signature doesn't match. Even taking generics into account, the return type of `GetItemAsync` is `Task<T>` that doesn't match the constraint `ITableBuilder<T>`.

**Comment by devtekve** [comment] 2024-05-11 16:54
I will try to figure out a way to prevent it from happening. If I give up, maybe we close this ?

**Comment by firenero** [comment] 2024-05-14 01:00
Yep, closing this one. If you find a way how to stop it from happening by changing the library code, please create another ticket for better visibility.

**Closed by firenero** 2024-05-14 01:00 UTC
